name: Cleanup Vercel Preview Deployments

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    name: Purge Preview Deployments
    runs-on: ubuntu-latest
    steps:
      - name: Delete Vercel Previews on Branch
        uses: BetaHuhn/delete-vercel-deployment-action@v1
        if: env.VERCEL_TOKEN != ''
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          ref: ${{ github.head_ref }}
          only-previews: true
